### ISSUE TITLE
Issue with notenoughwands:lightblock

### ISSUE THREAD

**Issue by kragnoth** [romelo333/notenoughwands1.8.8#19]
The lightblock made by the light wand has an overlayed text due to forge's new change in Build 1.11.2-13.20.0.2223:fry: Added the variant name to the missing model. (#3328)

Fry linked this following code as the source of the issue: https://github.com/romelo333/notenoughwands/blob/master/src/main/java/romelo333/notenoughwands/blocks/LightBlock.java#L53-L55

Here is a picture: 
![notenoughwands overlay](https://cloud.githubusercontent.com/assets/20483720/22620029/c2a3f6c2-ead0-11e6-81ae-22f908e1b0db.png)

This only happens in versions of forge 2223+ in minecraft 1.11.2.  I think this will happen in most versions of not enough wands for 1.11.2.

Thanks

**Comment by McJty** [comment]
Fixed next release
