### ISSUE TITLE
Wands deleating chests/tile entitys

### ISSUE THREAD

**Issue by tyler489** [romelo333/notenoughwands1.8.8#2]
if u use an illumination wand on a chest/tinkers forge while shift clicking it deleates the object.
Useing knoxz testpack for 1.9
 Notenoughwands 1.9.0.1.3.3

**Comment by McJty** [comment]
I cannot reproduce this. Do you also have this on vanilla chests? Exactly what do you do to reproduce this?

**Comment by tyler489** [comment]
yes

**Comment by McJty** [comment]
Strange... Not sure what to do about this. Might be some weird mod interaction

**Comment by McJty** [comment]
I found out how to reproduce. Will fix next version
