### ISSUE TITLE
[1.12]Moving Wand can be used to delete blocks

### ISSUE THREAD

**Issue by Darkhax** [romelo333/notenoughwands1.8.8#22]
Hello, 

Version 1.12-1.5.8

I noticed earlier today that you can use the moving wand to delete a block. To replicate this issue, use the moving wand to pick up a block. In my case I was using a wither skeleton spawner. Then take the block, and click on the side of an anvil. This will cause the block to be placed on the side of the block you interacted with, rather than opening the anvil GUI. Additionally, if there was a block in the position it will delete that block. I've attached a gif showing the issue. Not that while I only tested with non-solid blocks that don't take up the full block, you can delete full blocks as well. You can probably use this to permabreak the end portal, or other weird griefing too ;p

![animation](https://user-images.githubusercontent.com/2250798/27895632-43b6caba-61d1-11e7-9012-81a406d17c68.gif)

**Comment by McJty** [comment]
This bug has been fixed some time ago
