### ISSUE TITLE
(FEATURE SUGGESTION) Protection Wand prevents break, not break-replace immediately

### ISSUE THREAD

**Issue by Vaygrim** [romelo333/notenoughwands1.8.8#3]
(This suggestion is for the latest / 1.9.X branch)
I'd LOVE LOVE to see a very minor (but potentially a pain in the backside) change in the Protection Wand mechanics. 

Right now if you protect a block then try to break it, the block actually breaks then immediately replaces. Would it be possible to make it so the block never breaks in the first place? (I've got a big build I want to use in 1.9.4 with the N.E.W. Protection Wand.. but I don't want people to see 'behind' the block they're trying to break.) Small, cosmetic.. but I don't know if it's possible.

**Comment by ProfessorProspector** [comment]
I mean if they wanted to see behind it, they could still use like an xray mod, but good suggestion.

**Comment by McJty** [comment]
I'm not sure how easy this will be but we can have a look to see what's possible. I'm already happy you're suggesting this for the 1.9 release :-)

**Comment by Vaygrim** [comment]
The story behind this suggestion:

I've got big plans for a special pack for MC 1.9.4 and it will be centered around a key 'big build' the players start in. I think the Protection Wand might be the perfect way to keep certain wall blocks in corridors from being broken without resorting to full on 'Adventure Mode' craziness. Ideally, this would have the best 'visual appeal' if players couldn't ever see what's behind these locked down wall blocks, even briefly, by breaking them.

Just so you know WHY I'm requesting it.

**Comment by McJty** [comment]
Ok, I'm going to try to solve this problem but as a workaround you might consider making the walls two thick. That will also prevent them from looking through

**Comment by Vaygrim** [comment]
Big (BIG) spaceship design, with lots of "Chisels & Bits" design aspects on the walls. I suspect there will be another layer behind that in most cases, but I'm just suggesting this for edge cases.

For the record, if this isn't a possible thing I totally understand. This is just me doing a little 'wishing'. <3

**Comment by McJty** [comment]
I'll see what I can do in any case

**Comment by McJty** [comment]
I think I know a way how to solve this. Just have to think about how to efficiently implement it. The problem right now is that only the server knows about the protected blocks. So when you try to harvest the client simply goes on as usual until the server overrides that. If I can get this protected block information on the client too then that would solve the issue. Just have to find an efficient way to do this without having too much server->client network traffic

**Comment by McJty** [comment]
Implemented in the 1.9.4 version but disabled by default. Enable this in the config
