### ISSUE TITLE
Moving wand bypassing protection

### ISSUE THREAD

**Issue by bloodmc** [romelo333/notenoughwands1.8.8#30]
As per our discussion earlier, the moving wand is currently not firing any events and bypassing protection.

See https://github.com/MinecraftPortCentral/GriefPrevention/issues/830

I recommend firing a `BlockEvent.Place` for single block moves and `BlockEvent.Multi` for 2+ moves.

Thanks!

**Comment by McJty** [comment]
Fixed for the moving wand, the illumination wand and the displacement wand. The building wand and the swapping wand were already firing the proper events
