### ISSUE TITLE
Moving wand needs backlist

### ISSUE THREAD

**Issue by Dijkstra1-zz** [romelo333/notenoughwands1.8.8#9]
Moving wands, can move well everything? certain items just should not be moved
![2016-08-24_02 52 54](https://cloud.githubusercontent.com/assets/11648771/17933684/8d79eb48-6a04-11e6-9f4a-bf5b0d1555f2.png)
I fell sorry for the person that find that missing in the strong hold.
As well that i can move bedrock, and get other items that should not.
The mod should come with internal blacklist of items, including end portal, bedrock and other things, that players should have.

**Comment by McJty** [comment]
It has that already. There is a 'movingblacklist' config in the config file where you can add additional blocks

**Comment by Dijkstra1-zz** [comment]
I still think by default things like end portal should be in it :)

**Comment by McJty** [comment]
It actually has a blacklist and it is working now (in the next version). Also things like bedrock and end portal blocks are no longer movable
